parameters:
  gotakk.view_model.service.class: gotakk\ViewModelBundle\Services\ViewModelService

services:
  gotakk.view_model.service:
    class: %gotakk.view_model.service.class%
    arguments: [%gotakk.view_model.irregular_plurals.parameter%]
