language:
  - php

sudo: false

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1

install: composer install

script: phpunit --coverage-text --coverage-clover=coverage.xml

after_success:
  - php vendor/bin/coveralls
